### ISSUE TITLE
浅析 Redlock 分布式锁实现原理

### ISSUE THREAD

**Issue by her-cat** [her-cat/blog-comment#10]
https://her-cat.com/posts/2022/05/08/redlock-distributed-lock/? 

 在本文中，先介绍了单实例 Redis 锁的一些问题以及解决方法，然后介绍了基于多实例的 Redlock 分布式锁的实现，Redlock 在一定程度上提高了 Redis 锁的可用性以及扩展性。

**Comment by bcld** [comment]
图画的很详细，感谢分享。

**Comment by her-cat** [comment]
> @bcld
> 图画的很详细，感谢分享。
> 
> 

谢谢 😄
