### ISSUE TITLE
《PHP 实现 Base64 编码/解码》笔记

### ISSUE THREAD

**Issue by her-cat** [her-cat/blog-comment#33]
https://her-cat.com/posts/2020/02/10/php-implements-base64-encoding-decoding-notes/ 

 放假前，在《C Primer Plus》一书中阅读了关于位运算的章节，对于位运算的一些概念有了基本的认识，所以当静下心来阅读《PHP 实现 Base64 编码/解码》文中的

**Comment by MinsonLee** [comment]
裂图了

**Comment by her-cat** [comment]
> @MinsonLee
> 裂图了

已处理，感谢🙏
