### ISSUE TITLE
还原 SM2 压缩公钥的几种方法

### ISSUE THREAD

**Issue by her-cat** [her-cat/blog-comment#81]
https://her-cat.com/posts/2023/06/19/several-ways-to-decompress-sm2-compressed-public-key/ 

 在 SM2 算法中，公钥的大小为 64 字节，算上前缀 04 的话就是 65 字节。公钥由椭圆曲线上的坐标点（x, y）组成，即每个坐标点都是 32 字节的大数。为了节省存储空间，通常会对公钥进行压缩后使用，也就是压缩公钥。

**Comment by fainc** [comment]
不知道为什么gm情有独钟hex 😓
